[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
test = 'test'
solc_version = '0.8.24'
optimizer = true
optimizer_runs = 200
evm_version = 'cancun'
remappings = [
  'prb-math/=lib/prb-math/src/',
  'forge-std/=lib/forge-std/src/'
]

[fmt]
line_length = 110
multiline_func_header = 'all'
